// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/aead_api.dart';
import 'api/dsa_api.dart';
import 'api/hybrid_kem_api.dart';
import 'api/kem_api.dart';
import 'api/key_serialization_api.dart';
import 'api/secure_messaging_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DsaKeyPairDto dco_decode_dsa_key_pair_dto(dynamic raw);

  @protected
  EncapsulationDto dco_decode_encapsulation_dto(dynamic raw);

  @protected
  HybridEncapsulationDto dco_decode_hybrid_encapsulation_dto(dynamic raw);

  @protected
  HybridKeyPairDto dco_decode_hybrid_key_pair_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  KeyPairDto dco_decode_key_pair_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  SecurePackageDto dco_decode_secure_package_dto(dynamic raw);

  @protected
  TargetAeadAlgorithm dco_decode_target_aead_algorithm(dynamic raw);

  @protected
  TargetDsaAlgorithm dco_decode_target_dsa_algorithm(dynamic raw);

  @protected
  TargetHybridKemAlgorithm dco_decode_target_hybrid_kem_algorithm(dynamic raw);

  @protected
  TargetKemAlgorithm dco_decode_target_kem_algorithm(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DsaKeyPairDto sse_decode_dsa_key_pair_dto(SseDeserializer deserializer);

  @protected
  EncapsulationDto sse_decode_encapsulation_dto(SseDeserializer deserializer);

  @protected
  HybridEncapsulationDto sse_decode_hybrid_encapsulation_dto(
      SseDeserializer deserializer);

  @protected
  HybridKeyPairDto sse_decode_hybrid_key_pair_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  KeyPairDto sse_decode_key_pair_dto(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  SecurePackageDto sse_decode_secure_package_dto(SseDeserializer deserializer);

  @protected
  TargetAeadAlgorithm sse_decode_target_aead_algorithm(
      SseDeserializer deserializer);

  @protected
  TargetDsaAlgorithm sse_decode_target_dsa_algorithm(
      SseDeserializer deserializer);

  @protected
  TargetHybridKemAlgorithm sse_decode_target_hybrid_kem_algorithm(
      SseDeserializer deserializer);

  @protected
  TargetKemAlgorithm sse_decode_target_kem_algorithm(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_dsa_key_pair_dto(
      DsaKeyPairDto self, SseSerializer serializer);

  @protected
  void sse_encode_encapsulation_dto(
      EncapsulationDto self, SseSerializer serializer);

  @protected
  void sse_encode_hybrid_encapsulation_dto(
      HybridEncapsulationDto self, SseSerializer serializer);

  @protected
  void sse_encode_hybrid_key_pair_dto(
      HybridKeyPairDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_key_pair_dto(KeyPairDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_secure_package_dto(
      SecurePackageDto self, SseSerializer serializer);

  @protected
  void sse_encode_target_aead_algorithm(
      TargetAeadAlgorithm self, SseSerializer serializer);

  @protected
  void sse_encode_target_dsa_algorithm(
      TargetDsaAlgorithm self, SseSerializer serializer);

  @protected
  void sse_encode_target_hybrid_kem_algorithm(
      TargetHybridKemAlgorithm self, SseSerializer serializer);

  @protected
  void sse_encode_target_kem_algorithm(
      TargetKemAlgorithm self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
