// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/aead_api.dart';
import 'api/dsa_api.dart';
import 'api/hybrid_kem_api.dart';
import 'api/kem_api.dart';
import 'api/key_serialization_api.dart';
import 'api/secure_messaging_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -752130001;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'quantum_crypto',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<Uint8List> crateApiAeadApiAeadDecrypt(
      {required TargetAeadAlgorithm algorithm,
      required List<int> key,
      required List<int> ciphertextWithNonce});

  Future<Uint8List> crateApiAeadApiAeadEncrypt(
      {required TargetAeadAlgorithm algorithm,
      required List<int> key,
      required List<int> plaintext});

  Future<Uint8List> crateApiKeySerializationApiBase64ToBytes(
      {required String encoded});

  Future<Uint8List> crateApiKeySerializationApiBase64UrlSafeToBytes(
      {required String encoded});

  Future<String> crateApiKeySerializationApiBytesToBase64(
      {required List<int> data});

  Future<String> crateApiKeySerializationApiBytesToBase64UrlSafe(
      {required List<int> data});

  Future<String> crateApiKeySerializationApiBytesToHex(
      {required List<int> data});

  Future<Uint8List> crateApiSecureMessagingApiDecryptThenVerify(
      {required List<int> packageMlkemCiphertext,
      required List<int> packageX25519EphemeralPk,
      required List<int> packageEncryptedPayload,
      required TargetDsaAlgorithm dsaAlgorithm,
      required TargetHybridKemAlgorithm kemAlgorithm,
      required TargetAeadAlgorithm aeadAlgorithm,
      required List<int> recipientMlkemSecretKey,
      required List<int> recipientX25519SecretKey,
      required List<int> senderDsaPublicKey});

  Future<Uint8List> crateApiDsaApiDsaSign(
      {required TargetDsaAlgorithm algorithm,
      required List<int> message,
      required List<int> secretKey});

  Future<bool> crateApiDsaApiDsaVerify(
      {required TargetDsaAlgorithm algorithm,
      required List<int> message,
      required List<int> signature,
      required List<int> publicKey});

  Future<DsaKeyPairDto> crateApiDsaApiGenerateDsaKeypair(
      {required TargetDsaAlgorithm algorithm});

  Future<HybridKeyPairDto> crateApiHybridKemApiGenerateHybridKemKeypair(
      {required TargetHybridKemAlgorithm algorithm});

  Future<KeyPairDto> crateApiKemApiGenerateKemKeypair(
      {required TargetKemAlgorithm algorithm});

  Future<Uint8List> crateApiKeySerializationApiHexToBytes(
      {required String hex});

  Future<Uint8List> crateApiHybridKemApiHybridKemDecapsulate(
      {required TargetHybridKemAlgorithm algorithm,
      required List<int> mlkemCiphertext,
      required List<int> x25519EphemeralPk,
      required List<int> mlkemSecretKey,
      required List<int> x25519SecretKey});

  Future<HybridEncapsulationDto> crateApiHybridKemApiHybridKemEncapsulate(
      {required TargetHybridKemAlgorithm algorithm,
      required List<int> mlkemPublicKey,
      required List<int> x25519PublicKey});

  Future<Uint8List> crateApiKemApiKemDecapsulate(
      {required TargetKemAlgorithm algorithm,
      required List<int> ciphertext,
      required List<int> secretKey});

  Future<EncapsulationDto> crateApiKemApiKemEncapsulate(
      {required TargetKemAlgorithm algorithm, required List<int> publicKey});

  Future<SecurePackageDto> crateApiSecureMessagingApiSignThenEncrypt(
      {required TargetDsaAlgorithm dsaAlgorithm,
      required TargetHybridKemAlgorithm kemAlgorithm,
      required TargetAeadAlgorithm aeadAlgorithm,
      required List<int> message,
      required List<int> senderDsaSecretKey,
      required List<int> recipientMlkemPublicKey,
      required List<int> recipientX25519PublicKey});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Uint8List> crateApiAeadApiAeadDecrypt(
      {required TargetAeadAlgorithm algorithm,
      required List<int> key,
      required List<int> ciphertextWithNonce}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_target_aead_algorithm(algorithm, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_list_prim_u_8_loose(ciphertextWithNonce, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAeadApiAeadDecryptConstMeta,
      argValues: [algorithm, key, ciphertextWithNonce],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAeadApiAeadDecryptConstMeta => const TaskConstMeta(
        debugName: "aead_decrypt",
        argNames: ["algorithm", "key", "ciphertextWithNonce"],
      );

  @override
  Future<Uint8List> crateApiAeadApiAeadEncrypt(
      {required TargetAeadAlgorithm algorithm,
      required List<int> key,
      required List<int> plaintext}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_target_aead_algorithm(algorithm, serializer);
        sse_encode_list_prim_u_8_loose(key, serializer);
        sse_encode_list_prim_u_8_loose(plaintext, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAeadApiAeadEncryptConstMeta,
      argValues: [algorithm, key, plaintext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAeadApiAeadEncryptConstMeta => const TaskConstMeta(
        debugName: "aead_encrypt",
        argNames: ["algorithm", "key", "plaintext"],
      );

  @override
  Future<Uint8List> crateApiKeySerializationApiBase64ToBytes(
      {required String encoded}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(encoded, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiKeySerializationApiBase64ToBytesConstMeta,
      argValues: [encoded],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKeySerializationApiBase64ToBytesConstMeta =>
      const TaskConstMeta(
        debugName: "base64_to_bytes",
        argNames: ["encoded"],
      );

  @override
  Future<Uint8List> crateApiKeySerializationApiBase64UrlSafeToBytes(
      {required String encoded}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(encoded, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiKeySerializationApiBase64UrlSafeToBytesConstMeta,
      argValues: [encoded],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKeySerializationApiBase64UrlSafeToBytesConstMeta =>
      const TaskConstMeta(
        debugName: "base64_url_safe_to_bytes",
        argNames: ["encoded"],
      );

  @override
  Future<String> crateApiKeySerializationApiBytesToBase64(
      {required List<int> data}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(data, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiKeySerializationApiBytesToBase64ConstMeta,
      argValues: [data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKeySerializationApiBytesToBase64ConstMeta =>
      const TaskConstMeta(
        debugName: "bytes_to_base64",
        argNames: ["data"],
      );

  @override
  Future<String> crateApiKeySerializationApiBytesToBase64UrlSafe(
      {required List<int> data}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(data, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiKeySerializationApiBytesToBase64UrlSafeConstMeta,
      argValues: [data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKeySerializationApiBytesToBase64UrlSafeConstMeta =>
      const TaskConstMeta(
        debugName: "bytes_to_base64_url_safe",
        argNames: ["data"],
      );

  @override
  Future<String> crateApiKeySerializationApiBytesToHex(
      {required List<int> data}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(data, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiKeySerializationApiBytesToHexConstMeta,
      argValues: [data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKeySerializationApiBytesToHexConstMeta =>
      const TaskConstMeta(
        debugName: "bytes_to_hex",
        argNames: ["data"],
      );

  @override
  Future<Uint8List> crateApiSecureMessagingApiDecryptThenVerify(
      {required List<int> packageMlkemCiphertext,
      required List<int> packageX25519EphemeralPk,
      required List<int> packageEncryptedPayload,
      required TargetDsaAlgorithm dsaAlgorithm,
      required TargetHybridKemAlgorithm kemAlgorithm,
      required TargetAeadAlgorithm aeadAlgorithm,
      required List<int> recipientMlkemSecretKey,
      required List<int> recipientX25519SecretKey,
      required List<int> senderDsaPublicKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(packageMlkemCiphertext, serializer);
        sse_encode_list_prim_u_8_loose(packageX25519EphemeralPk, serializer);
        sse_encode_list_prim_u_8_loose(packageEncryptedPayload, serializer);
        sse_encode_target_dsa_algorithm(dsaAlgorithm, serializer);
        sse_encode_target_hybrid_kem_algorithm(kemAlgorithm, serializer);
        sse_encode_target_aead_algorithm(aeadAlgorithm, serializer);
        sse_encode_list_prim_u_8_loose(recipientMlkemSecretKey, serializer);
        sse_encode_list_prim_u_8_loose(recipientX25519SecretKey, serializer);
        sse_encode_list_prim_u_8_loose(senderDsaPublicKey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSecureMessagingApiDecryptThenVerifyConstMeta,
      argValues: [
        packageMlkemCiphertext,
        packageX25519EphemeralPk,
        packageEncryptedPayload,
        dsaAlgorithm,
        kemAlgorithm,
        aeadAlgorithm,
        recipientMlkemSecretKey,
        recipientX25519SecretKey,
        senderDsaPublicKey
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSecureMessagingApiDecryptThenVerifyConstMeta =>
      const TaskConstMeta(
        debugName: "decrypt_then_verify",
        argNames: [
          "packageMlkemCiphertext",
          "packageX25519EphemeralPk",
          "packageEncryptedPayload",
          "dsaAlgorithm",
          "kemAlgorithm",
          "aeadAlgorithm",
          "recipientMlkemSecretKey",
          "recipientX25519SecretKey",
          "senderDsaPublicKey"
        ],
      );

  @override
  Future<Uint8List> crateApiDsaApiDsaSign(
      {required TargetDsaAlgorithm algorithm,
      required List<int> message,
      required List<int> secretKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_target_dsa_algorithm(algorithm, serializer);
        sse_encode_list_prim_u_8_loose(message, serializer);
        sse_encode_list_prim_u_8_loose(secretKey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDsaApiDsaSignConstMeta,
      argValues: [algorithm, message, secretKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDsaApiDsaSignConstMeta => const TaskConstMeta(
        debugName: "dsa_sign",
        argNames: ["algorithm", "message", "secretKey"],
      );

  @override
  Future<bool> crateApiDsaApiDsaVerify(
      {required TargetDsaAlgorithm algorithm,
      required List<int> message,
      required List<int> signature,
      required List<int> publicKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_target_dsa_algorithm(algorithm, serializer);
        sse_encode_list_prim_u_8_loose(message, serializer);
        sse_encode_list_prim_u_8_loose(signature, serializer);
        sse_encode_list_prim_u_8_loose(publicKey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDsaApiDsaVerifyConstMeta,
      argValues: [algorithm, message, signature, publicKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDsaApiDsaVerifyConstMeta => const TaskConstMeta(
        debugName: "dsa_verify",
        argNames: ["algorithm", "message", "signature", "publicKey"],
      );

  @override
  Future<DsaKeyPairDto> crateApiDsaApiGenerateDsaKeypair(
      {required TargetDsaAlgorithm algorithm}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_target_dsa_algorithm(algorithm, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dsa_key_pair_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDsaApiGenerateDsaKeypairConstMeta,
      argValues: [algorithm],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDsaApiGenerateDsaKeypairConstMeta =>
      const TaskConstMeta(
        debugName: "generate_dsa_keypair",
        argNames: ["algorithm"],
      );

  @override
  Future<HybridKeyPairDto> crateApiHybridKemApiGenerateHybridKemKeypair(
      {required TargetHybridKemAlgorithm algorithm}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_target_hybrid_kem_algorithm(algorithm, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_hybrid_key_pair_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiHybridKemApiGenerateHybridKemKeypairConstMeta,
      argValues: [algorithm],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiHybridKemApiGenerateHybridKemKeypairConstMeta =>
      const TaskConstMeta(
        debugName: "generate_hybrid_kem_keypair",
        argNames: ["algorithm"],
      );

  @override
  Future<KeyPairDto> crateApiKemApiGenerateKemKeypair(
      {required TargetKemAlgorithm algorithm}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_target_kem_algorithm(algorithm, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_key_pair_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiKemApiGenerateKemKeypairConstMeta,
      argValues: [algorithm],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKemApiGenerateKemKeypairConstMeta =>
      const TaskConstMeta(
        debugName: "generate_kem_keypair",
        argNames: ["algorithm"],
      );

  @override
  Future<Uint8List> crateApiKeySerializationApiHexToBytes(
      {required String hex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(hex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiKeySerializationApiHexToBytesConstMeta,
      argValues: [hex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKeySerializationApiHexToBytesConstMeta =>
      const TaskConstMeta(
        debugName: "hex_to_bytes",
        argNames: ["hex"],
      );

  @override
  Future<Uint8List> crateApiHybridKemApiHybridKemDecapsulate(
      {required TargetHybridKemAlgorithm algorithm,
      required List<int> mlkemCiphertext,
      required List<int> x25519EphemeralPk,
      required List<int> mlkemSecretKey,
      required List<int> x25519SecretKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_target_hybrid_kem_algorithm(algorithm, serializer);
        sse_encode_list_prim_u_8_loose(mlkemCiphertext, serializer);
        sse_encode_list_prim_u_8_loose(x25519EphemeralPk, serializer);
        sse_encode_list_prim_u_8_loose(mlkemSecretKey, serializer);
        sse_encode_list_prim_u_8_loose(x25519SecretKey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiHybridKemApiHybridKemDecapsulateConstMeta,
      argValues: [
        algorithm,
        mlkemCiphertext,
        x25519EphemeralPk,
        mlkemSecretKey,
        x25519SecretKey
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiHybridKemApiHybridKemDecapsulateConstMeta =>
      const TaskConstMeta(
        debugName: "hybrid_kem_decapsulate",
        argNames: [
          "algorithm",
          "mlkemCiphertext",
          "x25519EphemeralPk",
          "mlkemSecretKey",
          "x25519SecretKey"
        ],
      );

  @override
  Future<HybridEncapsulationDto> crateApiHybridKemApiHybridKemEncapsulate(
      {required TargetHybridKemAlgorithm algorithm,
      required List<int> mlkemPublicKey,
      required List<int> x25519PublicKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_target_hybrid_kem_algorithm(algorithm, serializer);
        sse_encode_list_prim_u_8_loose(mlkemPublicKey, serializer);
        sse_encode_list_prim_u_8_loose(x25519PublicKey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_hybrid_encapsulation_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiHybridKemApiHybridKemEncapsulateConstMeta,
      argValues: [algorithm, mlkemPublicKey, x25519PublicKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiHybridKemApiHybridKemEncapsulateConstMeta =>
      const TaskConstMeta(
        debugName: "hybrid_kem_encapsulate",
        argNames: ["algorithm", "mlkemPublicKey", "x25519PublicKey"],
      );

  @override
  Future<Uint8List> crateApiKemApiKemDecapsulate(
      {required TargetKemAlgorithm algorithm,
      required List<int> ciphertext,
      required List<int> secretKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_target_kem_algorithm(algorithm, serializer);
        sse_encode_list_prim_u_8_loose(ciphertext, serializer);
        sse_encode_list_prim_u_8_loose(secretKey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiKemApiKemDecapsulateConstMeta,
      argValues: [algorithm, ciphertext, secretKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKemApiKemDecapsulateConstMeta =>
      const TaskConstMeta(
        debugName: "kem_decapsulate",
        argNames: ["algorithm", "ciphertext", "secretKey"],
      );

  @override
  Future<EncapsulationDto> crateApiKemApiKemEncapsulate(
      {required TargetKemAlgorithm algorithm, required List<int> publicKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_target_kem_algorithm(algorithm, serializer);
        sse_encode_list_prim_u_8_loose(publicKey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_encapsulation_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiKemApiKemEncapsulateConstMeta,
      argValues: [algorithm, publicKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiKemApiKemEncapsulateConstMeta =>
      const TaskConstMeta(
        debugName: "kem_encapsulate",
        argNames: ["algorithm", "publicKey"],
      );

  @override
  Future<SecurePackageDto> crateApiSecureMessagingApiSignThenEncrypt(
      {required TargetDsaAlgorithm dsaAlgorithm,
      required TargetHybridKemAlgorithm kemAlgorithm,
      required TargetAeadAlgorithm aeadAlgorithm,
      required List<int> message,
      required List<int> senderDsaSecretKey,
      required List<int> recipientMlkemPublicKey,
      required List<int> recipientX25519PublicKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_target_dsa_algorithm(dsaAlgorithm, serializer);
        sse_encode_target_hybrid_kem_algorithm(kemAlgorithm, serializer);
        sse_encode_target_aead_algorithm(aeadAlgorithm, serializer);
        sse_encode_list_prim_u_8_loose(message, serializer);
        sse_encode_list_prim_u_8_loose(senderDsaSecretKey, serializer);
        sse_encode_list_prim_u_8_loose(recipientMlkemPublicKey, serializer);
        sse_encode_list_prim_u_8_loose(recipientX25519PublicKey, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_secure_package_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSecureMessagingApiSignThenEncryptConstMeta,
      argValues: [
        dsaAlgorithm,
        kemAlgorithm,
        aeadAlgorithm,
        message,
        senderDsaSecretKey,
        recipientMlkemPublicKey,
        recipientX25519PublicKey
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSecureMessagingApiSignThenEncryptConstMeta =>
      const TaskConstMeta(
        debugName: "sign_then_encrypt",
        argNames: [
          "dsaAlgorithm",
          "kemAlgorithm",
          "aeadAlgorithm",
          "message",
          "senderDsaSecretKey",
          "recipientMlkemPublicKey",
          "recipientX25519PublicKey"
        ],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DsaKeyPairDto dco_decode_dsa_key_pair_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DsaKeyPairDto(
      publicKey: dco_decode_list_prim_u_8_strict(arr[0]),
      secretKey: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  EncapsulationDto dco_decode_encapsulation_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EncapsulationDto(
      ciphertext: dco_decode_list_prim_u_8_strict(arr[0]),
      sharedSecret: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  HybridEncapsulationDto dco_decode_hybrid_encapsulation_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HybridEncapsulationDto(
      mlkemCiphertext: dco_decode_list_prim_u_8_strict(arr[0]),
      x25519EphemeralPk: dco_decode_list_prim_u_8_strict(arr[1]),
      sharedSecret: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  HybridKeyPairDto dco_decode_hybrid_key_pair_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return HybridKeyPairDto(
      mlkemPublicKey: dco_decode_list_prim_u_8_strict(arr[0]),
      x25519PublicKey: dco_decode_list_prim_u_8_strict(arr[1]),
      mlkemSecretKey: dco_decode_list_prim_u_8_strict(arr[2]),
      x25519SecretKey: dco_decode_list_prim_u_8_strict(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  KeyPairDto dco_decode_key_pair_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return KeyPairDto(
      publicKey: dco_decode_list_prim_u_8_strict(arr[0]),
      secretKey: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  SecurePackageDto dco_decode_secure_package_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SecurePackageDto(
      mlkemCiphertext: dco_decode_list_prim_u_8_strict(arr[0]),
      x25519EphemeralPk: dco_decode_list_prim_u_8_strict(arr[1]),
      encryptedPayload: dco_decode_list_prim_u_8_strict(arr[2]),
      dsaAlgorithm: dco_decode_target_dsa_algorithm(arr[3]),
      kemAlgorithm: dco_decode_target_hybrid_kem_algorithm(arr[4]),
      aeadAlgorithm: dco_decode_target_aead_algorithm(arr[5]),
    );
  }

  @protected
  TargetAeadAlgorithm dco_decode_target_aead_algorithm(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TargetAeadAlgorithm.values[raw as int];
  }

  @protected
  TargetDsaAlgorithm dco_decode_target_dsa_algorithm(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TargetDsaAlgorithm.values[raw as int];
  }

  @protected
  TargetHybridKemAlgorithm dco_decode_target_hybrid_kem_algorithm(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TargetHybridKemAlgorithm.values[raw as int];
  }

  @protected
  TargetKemAlgorithm dco_decode_target_kem_algorithm(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TargetKemAlgorithm.values[raw as int];
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DsaKeyPairDto sse_decode_dsa_key_pair_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_secretKey = sse_decode_list_prim_u_8_strict(deserializer);
    return DsaKeyPairDto(publicKey: var_publicKey, secretKey: var_secretKey);
  }

  @protected
  EncapsulationDto sse_decode_encapsulation_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ciphertext = sse_decode_list_prim_u_8_strict(deserializer);
    var var_sharedSecret = sse_decode_list_prim_u_8_strict(deserializer);
    return EncapsulationDto(
        ciphertext: var_ciphertext, sharedSecret: var_sharedSecret);
  }

  @protected
  HybridEncapsulationDto sse_decode_hybrid_encapsulation_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mlkemCiphertext = sse_decode_list_prim_u_8_strict(deserializer);
    var var_x25519EphemeralPk = sse_decode_list_prim_u_8_strict(deserializer);
    var var_sharedSecret = sse_decode_list_prim_u_8_strict(deserializer);
    return HybridEncapsulationDto(
        mlkemCiphertext: var_mlkemCiphertext,
        x25519EphemeralPk: var_x25519EphemeralPk,
        sharedSecret: var_sharedSecret);
  }

  @protected
  HybridKeyPairDto sse_decode_hybrid_key_pair_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mlkemPublicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_x25519PublicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_mlkemSecretKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_x25519SecretKey = sse_decode_list_prim_u_8_strict(deserializer);
    return HybridKeyPairDto(
        mlkemPublicKey: var_mlkemPublicKey,
        x25519PublicKey: var_x25519PublicKey,
        mlkemSecretKey: var_mlkemSecretKey,
        x25519SecretKey: var_x25519SecretKey);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  KeyPairDto sse_decode_key_pair_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_secretKey = sse_decode_list_prim_u_8_strict(deserializer);
    return KeyPairDto(publicKey: var_publicKey, secretKey: var_secretKey);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  SecurePackageDto sse_decode_secure_package_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mlkemCiphertext = sse_decode_list_prim_u_8_strict(deserializer);
    var var_x25519EphemeralPk = sse_decode_list_prim_u_8_strict(deserializer);
    var var_encryptedPayload = sse_decode_list_prim_u_8_strict(deserializer);
    var var_dsaAlgorithm = sse_decode_target_dsa_algorithm(deserializer);
    var var_kemAlgorithm = sse_decode_target_hybrid_kem_algorithm(deserializer);
    var var_aeadAlgorithm = sse_decode_target_aead_algorithm(deserializer);
    return SecurePackageDto(
        mlkemCiphertext: var_mlkemCiphertext,
        x25519EphemeralPk: var_x25519EphemeralPk,
        encryptedPayload: var_encryptedPayload,
        dsaAlgorithm: var_dsaAlgorithm,
        kemAlgorithm: var_kemAlgorithm,
        aeadAlgorithm: var_aeadAlgorithm);
  }

  @protected
  TargetAeadAlgorithm sse_decode_target_aead_algorithm(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TargetAeadAlgorithm.values[inner];
  }

  @protected
  TargetDsaAlgorithm sse_decode_target_dsa_algorithm(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TargetDsaAlgorithm.values[inner];
  }

  @protected
  TargetHybridKemAlgorithm sse_decode_target_hybrid_kem_algorithm(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TargetHybridKemAlgorithm.values[inner];
  }

  @protected
  TargetKemAlgorithm sse_decode_target_kem_algorithm(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TargetKemAlgorithm.values[inner];
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_dsa_key_pair_dto(
      DsaKeyPairDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
    sse_encode_list_prim_u_8_strict(self.secretKey, serializer);
  }

  @protected
  void sse_encode_encapsulation_dto(
      EncapsulationDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.ciphertext, serializer);
    sse_encode_list_prim_u_8_strict(self.sharedSecret, serializer);
  }

  @protected
  void sse_encode_hybrid_encapsulation_dto(
      HybridEncapsulationDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.mlkemCiphertext, serializer);
    sse_encode_list_prim_u_8_strict(self.x25519EphemeralPk, serializer);
    sse_encode_list_prim_u_8_strict(self.sharedSecret, serializer);
  }

  @protected
  void sse_encode_hybrid_key_pair_dto(
      HybridKeyPairDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.mlkemPublicKey, serializer);
    sse_encode_list_prim_u_8_strict(self.x25519PublicKey, serializer);
    sse_encode_list_prim_u_8_strict(self.mlkemSecretKey, serializer);
    sse_encode_list_prim_u_8_strict(self.x25519SecretKey, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_key_pair_dto(KeyPairDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
    sse_encode_list_prim_u_8_strict(self.secretKey, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_secure_package_dto(
      SecurePackageDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.mlkemCiphertext, serializer);
    sse_encode_list_prim_u_8_strict(self.x25519EphemeralPk, serializer);
    sse_encode_list_prim_u_8_strict(self.encryptedPayload, serializer);
    sse_encode_target_dsa_algorithm(self.dsaAlgorithm, serializer);
    sse_encode_target_hybrid_kem_algorithm(self.kemAlgorithm, serializer);
    sse_encode_target_aead_algorithm(self.aeadAlgorithm, serializer);
  }

  @protected
  void sse_encode_target_aead_algorithm(
      TargetAeadAlgorithm self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_target_dsa_algorithm(
      TargetDsaAlgorithm self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_target_hybrid_kem_algorithm(
      TargetHybridKemAlgorithm self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_target_kem_algorithm(
      TargetKemAlgorithm self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
