[package]
name = "quantum_crypto"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.12.0"
pqcrypto-mldsa = "0.1.2"
pqcrypto-mlkem = "0.1.1"
pqcrypto-traits = "0.3.5"
zeroize = { version = "1.9.0", features = ["zeroize_derive"] }
x25519-dalek = { version = "2.0", features = ["static_secrets"] }
hkdf = "0.12"
sha2 = "0.10"
rand_core = { version = "0.6", features = ["getrandom"] }
aes-gcm = "0.10"
chacha20poly1305 = "0.10"
base64 = "0.22"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }


[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
