// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`

Future<Uint8List> aeadEncrypt({
  required TargetAeadAlgorithm algorithm,
  required List<int> key,
  required List<int> plaintext,
}) =>
    RustLib.instance.api.crateApiAeadApiAeadEncrypt(
      algorithm: algorithm,
      key: key,
      plaintext: plaintext,
    );

Future<Uint8List> aeadDecrypt({
  required TargetAeadAlgorithm algorithm,
  required List<int> key,
  required List<int> ciphertextWithNonce,
}) =>
    RustLib.instance.api.crateApiAeadApiAeadDecrypt(
      algorithm: algorithm,
      key: key,
      ciphertextWithNonce: ciphertextWithNonce,
    );

enum TargetAeadAlgorithm { aes256Gcm, chaCha20Poly1305 }
