// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`

Future<DsaKeyPairDto> generateDsaKeypair({
  required TargetDsaAlgorithm algorithm,
}) =>
    RustLib.instance.api.crateApiDsaApiGenerateDsaKeypair(algorithm: algorithm);

Future<Uint8List> dsaSign({
  required TargetDsaAlgorithm algorithm,
  required List<int> message,
  required List<int> secretKey,
}) =>
    RustLib.instance.api.crateApiDsaApiDsaSign(
      algorithm: algorithm,
      message: message,
      secretKey: secretKey,
    );

Future<bool> dsaVerify({
  required TargetDsaAlgorithm algorithm,
  required List<int> message,
  required List<int> signature,
  required List<int> publicKey,
}) =>
    RustLib.instance.api.crateApiDsaApiDsaVerify(
      algorithm: algorithm,
      message: message,
      signature: signature,
      publicKey: publicKey,
    );

class DsaKeyPairDto {
  final Uint8List publicKey;
  final Uint8List secretKey;

  const DsaKeyPairDto({required this.publicKey, required this.secretKey});

  @override
  int get hashCode => publicKey.hashCode ^ secretKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DsaKeyPairDto &&
          runtimeType == other.runtimeType &&
          publicKey == other.publicKey &&
          secretKey == other.secretKey;
}

enum TargetDsaAlgorithm { mlDsa44, mlDsa65, mlDsa87 }
