// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`

Future<HybridKeyPairDto> generateHybridKemKeypair({
  required TargetHybridKemAlgorithm algorithm,
}) =>
    RustLib.instance.api.crateApiHybridKemApiGenerateHybridKemKeypair(
      algorithm: algorithm,
    );

Future<HybridEncapsulationDto> hybridKemEncapsulate({
  required TargetHybridKemAlgorithm algorithm,
  required List<int> mlkemPublicKey,
  required List<int> x25519PublicKey,
}) =>
    RustLib.instance.api.crateApiHybridKemApiHybridKemEncapsulate(
      algorithm: algorithm,
      mlkemPublicKey: mlkemPublicKey,
      x25519PublicKey: x25519PublicKey,
    );

Future<Uint8List> hybridKemDecapsulate({
  required TargetHybridKemAlgorithm algorithm,
  required List<int> mlkemCiphertext,
  required List<int> x25519EphemeralPk,
  required List<int> mlkemSecretKey,
  required List<int> x25519SecretKey,
}) =>
    RustLib.instance.api.crateApiHybridKemApiHybridKemDecapsulate(
      algorithm: algorithm,
      mlkemCiphertext: mlkemCiphertext,
      x25519EphemeralPk: x25519EphemeralPk,
      mlkemSecretKey: mlkemSecretKey,
      x25519SecretKey: x25519SecretKey,
    );

class HybridEncapsulationDto {
  final Uint8List mlkemCiphertext;
  final Uint8List x25519EphemeralPk;
  final Uint8List sharedSecret;

  const HybridEncapsulationDto({
    required this.mlkemCiphertext,
    required this.x25519EphemeralPk,
    required this.sharedSecret,
  });

  @override
  int get hashCode =>
      mlkemCiphertext.hashCode ^
      x25519EphemeralPk.hashCode ^
      sharedSecret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HybridEncapsulationDto &&
          runtimeType == other.runtimeType &&
          mlkemCiphertext == other.mlkemCiphertext &&
          x25519EphemeralPk == other.x25519EphemeralPk &&
          sharedSecret == other.sharedSecret;
}

class HybridKeyPairDto {
  final Uint8List mlkemPublicKey;
  final Uint8List x25519PublicKey;
  final Uint8List mlkemSecretKey;
  final Uint8List x25519SecretKey;

  const HybridKeyPairDto({
    required this.mlkemPublicKey,
    required this.x25519PublicKey,
    required this.mlkemSecretKey,
    required this.x25519SecretKey,
  });

  @override
  int get hashCode =>
      mlkemPublicKey.hashCode ^
      x25519PublicKey.hashCode ^
      mlkemSecretKey.hashCode ^
      x25519SecretKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HybridKeyPairDto &&
          runtimeType == other.runtimeType &&
          mlkemPublicKey == other.mlkemPublicKey &&
          x25519PublicKey == other.x25519PublicKey &&
          mlkemSecretKey == other.mlkemSecretKey &&
          x25519SecretKey == other.x25519SecretKey;
}

enum TargetHybridKemAlgorithm {
  mlKem512X25519,
  mlKem768X25519,
  mlKem1024X25519,
}
