// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Derive key material from a shared secret using HKDF-SHA256.
///
/// * `shared_secret` - Input keying material (e.g., from KEM encapsulation)
/// * `salt` - Optional salt (if empty, a default salt is used)
/// * `info` - Context/application-specific info string
/// * `output_len` - Desired output length in bytes (1-8160)
Future<Uint8List> hkdfDerive({
  required List<int> sharedSecret,
  required List<int> salt,
  required List<int> info,
  required int outputLen,
}) =>
    RustLib.instance.api.crateApiKdfApiHkdfDerive(
      sharedSecret: sharedSecret,
      salt: salt,
      info: info,
      outputLen: outputLen,
    );

/// Derive multiple keys from a shared secret in one call.
/// Returns a vector of derived keys, one for each entry in `info_strings`.
///
/// * `shared_secret` - Input keying material
/// * `salt` - Optional salt
/// * `info_strings` - Vector of context strings, one per desired key
/// * `key_length` - Length of each derived key in bytes
Future<List<Uint8List>> hkdfDeriveMulti({
  required List<int> sharedSecret,
  required List<int> salt,
  required List<String> infoStrings,
  required int keyLength,
}) =>
    RustLib.instance.api.crateApiKdfApiHkdfDeriveMulti(
      sharedSecret: sharedSecret,
      salt: salt,
      infoStrings: infoStrings,
      keyLength: keyLength,
    );
