// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<KeyPairDto> mlKem768GenerateKeyPair() =>
    RustLib.instance.api.crateApiKemMlKem768GenerateKeyPair();

Future<EncapsulationDto> mlKem768Encapsulate({required List<int> publicKey}) =>
    RustLib.instance.api.crateApiKemMlKem768Encapsulate(publicKey: publicKey);

Future<Uint8List> mlKem768Decapsulate(
        {required List<int> ciphertext, required List<int> secretKey}) =>
    RustLib.instance.api.crateApiKemMlKem768Decapsulate(
        ciphertext: ciphertext, secretKey: secretKey);

class EncapsulationDto {
  final Uint8List ciphertext;
  final Uint8List sharedSecret;

  const EncapsulationDto({
    required this.ciphertext,
    required this.sharedSecret,
  });

  @override
  int get hashCode => ciphertext.hashCode ^ sharedSecret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncapsulationDto &&
          runtimeType == other.runtimeType &&
          ciphertext == other.ciphertext &&
          sharedSecret == other.sharedSecret;
}

class KeyPairDto {
  final Uint8List publicKey;
  final Uint8List secretKey;

  const KeyPairDto({
    required this.publicKey,
    required this.secretKey,
  });

  @override
  int get hashCode => publicKey.hashCode ^ secretKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyPairDto &&
          runtimeType == other.runtimeType &&
          publicKey == other.publicKey &&
          secretKey == other.secretKey;
}
