// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> bytesToHex({required List<int> data}) =>
    RustLib.instance.api.crateApiKeySerializationApiBytesToHex(data: data);

Future<Uint8List> hexToBytes({required String hex}) =>
    RustLib.instance.api.crateApiKeySerializationApiHexToBytes(hex: hex);

Future<String> bytesToBase64({required List<int> data}) =>
    RustLib.instance.api.crateApiKeySerializationApiBytesToBase64(data: data);

Future<Uint8List> base64ToBytes({required String encoded}) =>
    RustLib.instance.api
        .crateApiKeySerializationApiBase64ToBytes(encoded: encoded);

Future<String> bytesToBase64UrlSafe({required List<int> data}) =>
    RustLib.instance.api
        .crateApiKeySerializationApiBytesToBase64UrlSafe(data: data);

Future<Uint8List> base64UrlSafeToBytes({required String encoded}) =>
    RustLib.instance.api
        .crateApiKeySerializationApiBase64UrlSafeToBytes(encoded: encoded);
