// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generate a cryptographically secure random 32-byte master seed.
Future<Uint8List> generateMasterSeed() =>
    RustLib.instance.api.crateApiSeedKeygenApiGenerateMasterSeed();

/// Derive key material from a master seed using HKDF-SHA256.
///
/// * `seed` - Master seed (>= 32 bytes)
/// * `purpose` - Domain separation string (e.g., "x25519-private-key")
/// * `key_index` - Index for deriving multiple keys of the same purpose
/// * `output_len` - Desired output length in bytes (1-8160)
Future<Uint8List> deriveKeyFromSeed({
  required List<int> seed,
  required String purpose,
  required int keyIndex,
  required int outputLen,
}) =>
    RustLib.instance.api.crateApiSeedKeygenApiDeriveKeyFromSeed(
      seed: seed,
      purpose: purpose,
      keyIndex: keyIndex,
      outputLen: outputLen,
    );

/// Derive a 32-byte X25519 private key deterministically from seed.
Future<Uint8List> deriveX25519FromSeed({
  required List<int> seed,
  required int keyIndex,
}) =>
    RustLib.instance.api.crateApiSeedKeygenApiDeriveX25519FromSeed(
      seed: seed,
      keyIndex: keyIndex,
    );

/// Derive a 32-byte AEAD symmetric key deterministically from seed.
Future<Uint8List> deriveAeadKeyFromSeed({
  required List<int> seed,
  required int keyIndex,
}) =>
    RustLib.instance.api.crateApiSeedKeygenApiDeriveAeadKeyFromSeed(
      seed: seed,
      keyIndex: keyIndex,
    );
