// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'aead_api.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Encrypt data using streaming/chunked AEAD encryption.
/// Suitable for large files. Data is split into chunks and each chunk
/// is encrypted independently with a counter-based nonce.
///
/// * `algorithm` - AEAD algorithm to use
/// * `key` - 32-byte encryption key
/// * `plaintext` - Data to encrypt
/// * `chunk_size` - Optional chunk size in bytes (default: 65536 = 64KB)
Future<Uint8List> streamAeadEncrypt({
  required TargetAeadAlgorithm algorithm,
  required List<int> key,
  required List<int> plaintext,
  int? chunkSize,
}) =>
    RustLib.instance.api.crateApiStreamingApiStreamAeadEncrypt(
      algorithm: algorithm,
      key: key,
      plaintext: plaintext,
      chunkSize: chunkSize,
    );

/// Decrypt data that was encrypted with streaming/chunked AEAD encryption.
///
/// * `key` - 32-byte decryption key
/// * `encrypted_data` - The full encrypted stream (header + chunks)
Future<Uint8List> streamAeadDecrypt({
  required List<int> key,
  required List<int> encryptedData,
}) =>
    RustLib.instance.api.crateApiStreamingApiStreamAeadDecrypt(
      key: key,
      encryptedData: encryptedData,
    );
